// The nine real קריית גת lotteries of the May 2026 round, exactly as the
// ministry's API returned them, trimmed to the fields the model reads.
//
// This is the round research/dira-behanacha-research.html validated against, so
// the city-level results computed from it are the published numbers, and any
// drift in the model shows up as a failing assertion rather than as a
// plausible-looking bar. Values are transcribed straight from the API.

export const KIRYAT_GAT_MAY_2026 = [
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2696",
    LotteryApparmentsNum: 303,
    HousingUnitsForHandicapped: 10,
    HU_CombatReservist_L: 75,
    HU_Reservists_L: 76,
    LocalHousing: 60,
    TotalSubscribers: 25231,
    TotalLocalSubscribers: 908,
    TotalHandicappedSubscribers: 10,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2697",
    LotteryApparmentsNum: 245,
    HousingUnitsForHandicapped: 8,
    HU_CombatReservist_L: 61,
    HU_Reservists_L: 61,
    LocalHousing: 48,
    TotalSubscribers: 25307,
    TotalLocalSubscribers: 938,
    TotalHandicappedSubscribers: 10,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2698",
    LotteryApparmentsNum: 207,
    HousingUnitsForHandicapped: 6,
    HU_CombatReservist_L: 51,
    HU_Reservists_L: 52,
    LocalHousing: 41,
    TotalSubscribers: 25039,
    TotalLocalSubscribers: 909,
    TotalHandicappedSubscribers: 8,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2699",
    LotteryApparmentsNum: 193,
    HousingUnitsForHandicapped: 6,
    HU_CombatReservist_L: 48,
    HU_Reservists_L: 48,
    LocalHousing: 38,
    TotalSubscribers: 25153,
    TotalLocalSubscribers: 908,
    TotalHandicappedSubscribers: 8,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2700",
    LotteryApparmentsNum: 183,
    HousingUnitsForHandicapped: 6,
    HU_CombatReservist_L: 45,
    HU_Reservists_L: 46,
    LocalHousing: 36,
    TotalSubscribers: 25067,
    TotalLocalSubscribers: 905,
    TotalHandicappedSubscribers: 8,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2705",
    LotteryApparmentsNum: 114,
    HousingUnitsForHandicapped: 3,
    HU_CombatReservist_L: 28,
    HU_Reservists_L: 29,
    LocalHousing: 22,
    TotalSubscribers: 24938,
    TotalLocalSubscribers: 889,
    TotalHandicappedSubscribers: 8,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2706",
    LotteryApparmentsNum: 78,
    HousingUnitsForHandicapped: 2,
    HU_CombatReservist_L: 19,
    HU_Reservists_L: 20,
    LocalHousing: 15,
    TotalSubscribers: 24838,
    TotalLocalSubscribers: 884,
    TotalHandicappedSubscribers: 8,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2707",
    LotteryApparmentsNum: 72,
    HousingUnitsForHandicapped: 2,
    HU_CombatReservist_L: 18,
    HU_Reservists_L: 18,
    LocalHousing: 14,
    TotalSubscribers: 24834,
    TotalLocalSubscribers: 882,
    TotalHandicappedSubscribers: 8,
  },
  {
    CityDescription: "קריית גת",
    NeighborhoodName: "שכ' מערבית",
    LotteryNumber: "2708",
    LotteryApparmentsNum: 38,
    HousingUnitsForHandicapped: 1,
    HU_CombatReservist_L: 9,
    HU_Reservists_L: 10,
    LocalHousing: 7,
    TotalSubscribers: 24856,
    TotalLocalSubscribers: 882,
    TotalHandicappedSubscribers: 8,
  },
];
